input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { "message" => "%{COMBINEDAPACHELOG}" }
    ecs_compatibility => disabled
    tag_on_failure => ["not_access_log"]
  }

  if "not_access_log" not in [tags] {
    mutate {
      convert => { "response" => "integer" "bytes" => "integer" }
      add_field => { "log_type" => "access" }
    }
    date {
      match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
      target => "@timestamp"
    }
  } else {
    mutate {
      add_field => { "log_type" => "app" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nexvion-logs-%{+YYYY.MM.dd}"
  }
}
